name: Sync to Hugging Face Spaces

on:
  push:
    branches: [main]
    paths:
      - 'attendx-backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push Subtree to HF
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "bot@attendx.com"
          git config --global user.name "AttendX Bot"
          
          # Create a temporary local branch of the folder
          git subtree split --prefix attendx-backend -b deploy-branch
          
          # Force push to Hugging Face
          git push https://sambhavvoswal:$HF_TOKEN@huggingface.co/spaces/sambhavvoswal/attendx-backend deploy-branch:main --force
